plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  # Always enable new cops, disabling manually when they don't fit.
  EnabledByDefault: true
  NewCops: enable

# ------------------------------------------------------------------------------
# Cops excluded for specific directories
# ------------------------------------------------------------------------------

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Copyright:
  AutocorrectNotice: |
    # Copyright (c) Valencia Management Group
    # All rights reserved.
  Notice: |
    Copyright \(c\) Valencia Management Group
    All rights reserved.

# ------------------------------------------------------------------------------
# Cops that should not be run
# ------------------------------------------------------------------------------

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

# Recommends `::File` instead of `File`
Lint/ConstantResolution:
  Enabled: false

# Recommends Integer(xxx, 10) instead of xxx.to_i
Lint/NumberConversion:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

# Every method should be documented, but I'm not *that* professional.
Style/DocumentationMethod:
  Enabled: false

# Converts `.to eq 1` to `.to(eq(1))`
Style/MethodCallWithArgsParentheses:
  Enabled: false

# This is just for setting HTTParty's request headers
Style/StringHashKeys:
  Enabled: false

# Forbids the use of "rubocop:disable"
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false
